image: docker:latest
variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
  - list-images
  - test
  - push
  - deploy

services:
  - docker:24.0.5-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yaml build
  timeout: 20m
  artifacts:
    paths:
      - docker-compose.yaml

list-images:
  stage: list-images
  script:
    - echo "Listing Docker images..."
    - docker images

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yaml up -d
    - docker-compose -f docker-compose.yaml exec api-gateway npm test -- --coverage
    - docker-compose -f docker-compose.yaml exec auth-service npm test -- --coverage
    - docker-compose -f docker-compose.yaml exec order-service npm test -- --coverage
    - docker-compose -f docker-compose.yaml exec product-service npm test -- --coverage
  artifacts:
    paths:
      - coverage/

push:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker-compose -f docker-compose.yaml push

deploy:
  stage: deploy
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker-compose -f docker-compose.yaml pull
    - docker-compose -f docker-compose.yaml up -d
  only:
    - main
