image: docker:latest
variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - push
  - deploy

services:
  - docker:24.0.5-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yaml build
    - docker tag api-gateway ericamaya29/api-gateway:latest
    - docker tag auth-service ericamaya29/auth-service:latest
    - docker tag order-service ericamaya29/order-service:latest
    - docker tag product-service ericamaya29/product-service:latest
  timeout: 20m
  artifacts:
    paths:
      - docker-compose.yaml

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yaml up -d
    - docker-compose -f docker-compose.yaml exec api-gateway npm test -- --coverage
    - docker-compose -f docker-compose.yaml exec auth-service npm test -- --coverage
    - docker-compose -f docker-compose.yaml exec order-service npm test -- --coverage
    - docker-compose -f docker-compose.yaml exec product-service npm test -- --coverage
  artifacts:
    paths:
      - coverage/

push:
  stage: push
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker-compose -f docker-compose.yaml push

deploy:
  stage: deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker-compose -f docker-compose.yaml pull
    - docker-compose -f docker-compose.yaml up -d
  only:
    - main
