version: '3'

services:
  api-gateway:
    build: ./grpc-nest-proto-api-gateway-main 
    container_name: api-gateway-restock
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_URL=auth-service:5051
      - ORDER_SERVICE_URL=order-service:5052
      - PRODUCT_SERVICE_URL=product-service:5053
    depends_on:
      - auth-service
      - order-service
      - product-service

  auth-service:
    build: ./grpc-nest-proto-auth-ms-main
    container_name: auth-service
    ports:
      - '5051:5051'
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=ms_auth
    depends_on:
      - db

  order-service:
    build: ./grpc-nest-proto-order-ms-main
    container_name: order-service
    ports:
      - '5052:5052'
    environment:
      - NODE_ENV=production 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=ms_order
      - AUTH_SERVICE_URL=auth-service:5051
      - PRODUCT_SERVICE_URL=product-service:5053
    depends_on:
      - db

  product-service:
    build: ./grpc-nest-proto-product-ms-main
    container_name: product-service
    ports:
      - '5053:5053'
    environment:
      - NODE_ENV=production 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=ms_product
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ms_auth
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
